### ISSUE TITLE
Provide directions/example of using a national population grid as alternative to GHSL population layer

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#213]
I tested and confirmed that an analysis can be confirmed using an alternative population grid to the GHSL population layer.   I set up an analysis to use Australia's 2021 1km population  grid:

```
    australia_population_2021:
        pop_min_threshold: 5
        # urban sample points intersecting grid cells with estimated population less than this will be excluded from analysis
        alias: APG21e_1_0_0
        name: "Australian Population Grid 2021 (ABS, 2023)"
        data_name: APG21e_1_0_0
        data_dir: population_grids/Australian_Population_Grid_2021_in_TIFF_format
        data_type: raster:Int64
        crs_name: GDA94 / Australian Albers
        crs_standard: EPSG
        crs_srid: 3577
        source_url: https://www.abs.gov.au/statistics/people/population/regional-population/2021/GEOTIFF.zip
        date_acquired: 20230302
        year_published: 2022
        year_target: 2021
        provider: EU JRC
        licence: CC BY 4.0
        licence_url: https://www.abs.gov.au/website-privacy-copyright-and-disclaimer#copyright-and-creative-commons
        resolution: 1km
        raster_band: 1
        raster_nodata: 
        citation: "Australian Bureau of Statistics (2022), Australian Population Grid 2021. https://www.abs.gov.au/statistics/people/population/regional-population/2021"
```

This `australia_population_2021` dataset was setup as the population layer to be used for an analysis of Melbourne; it worked!

So, we shoud

- [ ] include an example for this -- perhaps an alternative configuration for Las Palmas de Gran Canaria using an official Spanish grid.  
- [ ] write about this in the documentation.

(Likewise I think we should also consider the possibilities that people could run this bringing all their own data: roads, intersections, points of interest, areas of interest.  We support some of this now (POIs), however for cities where such official data is available it could be desirable to use this, while still offering the use of OpenStreetMap as an option/default.)
