### ISSUE TITLE
Potential issue with custom points of interest

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#357]
### Discussed in https://github.com/global-healthy-liveable-cities/global-indicators/discussions/355

<div type='discussions-op-text'>

<sup>Originally posted by **gigioLR** August  1, 2023</sup>
Hi, we are testing some customized points of interest for Porto Alegre, but a problem emerged. 

During the "compile destinations" subprocess, it shows an error that "name 'engine' is not defined", even though we ran the software for the same city without the custom data.

```
Traceback (most recent call last):
  File "/home/ghsci/process/subprocesses/_05_compile_destinations.py", line 207, in <module>
    main()
  File "/home/ghsci/process/subprocesses/_05_compile_destinations.py", line 203, in main
    compile_destinations(codename)
  File "/home/ghsci/process/subprocesses/_05_compile_destinations.py", line 184, in compile_destinations
    custom_destination_setup(engine, r)
NameError: name 'engine' is not defined
```

In the YML for Porto Alegre, we used those parameters for the custom POI:

```
custom_destinations:
    ## nome do arquivo relativo ao diretório de dados do projeto
    file: other_custom_data/estabelecimentos_classificados_JCBV.csv
    ## nome simples da categoria
    dest_name: DESC_CNAE
    ## nome completo da categoria
    dest_name_full: DESC_CNAE
    ## coordenada y
    lat: LATITUDE
    ## coordenada x
    lon: LONGITUDE
    ## código EPSG
    epsg: 4326
    ## uma citação para esses dados
    citation: "Projeto Ambientes Alimentares"
    #########
```

It seems like the error happens before reading the CSV, is it our mistake or should we open an issue?

Also, can we use different categories than the ones in the "osm_destination_definitions.csv"? What the columns should have?</div>
