### ISSUE TITLE
Custom data import should be easier/more flexible/with more informative logging/reporting

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#397]
There are situations where OpenStreetMap data may not be adequate for particular destination types of interest in an indicator analysis of access to closest destination.  A work around for this is use of custom data, which can optionally be specified in the region configuration file.  

However, there are some limitations to the current implementation.  The current approach,

- assumes custom data to be provided in a single CSV with a pre-specified format; as user would have to combine multiple destinations into this one file and format
- requirement of a 'name field' and 'description' is arguably redundant; categories of destinations could be specified in the configuration file, and need not be present in the data itself
- option of different file types should be supported (e.g. geopackage, geojson, csv); the specifying of lat/lon fields is really only relevant for CSV or text delimited data.

**Describe the solution you'd like**
Allow users to specify data in a more flexible list like way, e.g. like GTFS feeds and other data

```
custom_destinations:
   pt_any:
       # name of file relative to project data directory
       file:
        ## The name of the provider of this data, e.g. Centro Nacional de Información Geográfica
        source: 
        ## Publication date for study region area data source, or date of currency, e.g. 2019-02-01
        publication_date: 
        ## URL for the source dataset, or its provider, e.g. https://datos.gob.es/en/catalogo/e00125901-spaignllm
        url: 
        ## Licence for the data, e.g. CC-BY-4.0
        licence: 
       # EPSG code
       epsg:
       # y coordinate (optional, only required for text-delimited data formats such as CSV)
       y_coordinate:       
       # x coordinate (optional, only required for text-delimited data formats such as CSV)
       x_coordinate  
   pt_frequent_20:
       # name of file relative to project data directory
       file:
        ## The name of the provider of this data, e.g. Centro Nacional de Información Geográfica
        source: 
        ## Publication date for study region area data source, or date of currency, e.g. 2019-02-01
        publication_date: 
        ## URL for the source dataset, or its provider, e.g. https://datos.gob.es/en/catalogo/e00125901-spaignllm
        url: 
        ## Licence for the data, e.g. CC-BY-4.0
        licence: 
       # EPSG code
       epsg:
       # y coordinate (optional, only required for text-delimited data formats such as CSV)
       y_coordinate:       
       # x coordinate (optional, only required for text-delimited data formats such as CSV)
       x_coordinate  
```

In addition, support should be made for

- alternatives to GTFS (ie. pre-identified stops with frequent service as per those required for our indicators)
- alternatives for areas of interest (ie. polygons, not just points)
- detailing what has been imported as custom data in the logging output, validation report, and possibly GUI
